name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    # needs:
    #   - publish_to_pypi
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "publish_to_pypi"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Proceed only if build succeeded
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          echo "The build passed! Starting the next task..."
      - name: Handle build failure or timeout
        if: steps.wait-for-build.outputs.conclusion == 'failure' || steps.wait-for-build.outputs.conclusion == 'timed_out'
        run: |
          echo "The build failed or timed out. Exiting gracefully or performing cleanup..."
          exit 1

      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Get PyPI package version
        id: get_version
        run: |
          VERSION=$(curl -s https://pypi.org/rss/project/SigmaFlow/releases.xml | grep -oP '<title>\K[^<]+' | sed -n '2p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected PyPI version: $VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ai4drug/sigmaflow

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ai4drug/sigmaflow:v${{ steps.get_version.outputs.VERSION }}
            ai4drug/sigmaflow:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/ai4drug/sigmaflow
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Send finish msg
        run:
          curl https://api.day.app/ozCgXAen6CwTabCZRPJfRQ/github/sigmaflow:%20docker%20publish%20done?icon=https://avatars1.githubusercontent.com/u/9919&group=github_action
